### ISSUE TITLE
Malware Detect ?

### ISSUE THREAD

**Issue by Itami-Youji** [L1ghtM4n/TorProxy#1]
Codeline 13: https://github.com/L1ghtM4n/TorProxy/blob/81b3f890be50c2a84e588b865ba54dccae22769c/SRC/TorBundle/BundleLoader.cs#L13

I think you have converted all files in an sfx file into an exe. And that's why it is recognized by some AV programs !
Would it be possible to change your download link? You could use the one from the gate yourself, you just have to unzip it
Download link : https://dist.torproject.org/torbrowser/11.0.2/tor-win32-0.4.6.8.zip

But nice work !

**Comment by L1ghtM4n** [comment]
Fixed.

https://github.com/L1ghtM4n/TorProxy/commit/f65b93dbb4debdc9e87069d1e8b44f549fdb589d
